# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  aws_auth_acc: 
    type: string
    default: $aws_auth_acc
  aws_auth_sec: 
    type: string
    default: $aws_auth_sec


jobs:
  create_vm:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: "create auth file"
          command: |
            cat > terraform/terraform-aws-ec2-nginx-main/terraform.tfvars \<< EOL
            aws_access_key = "<< pipeline.parameters.aws_auth_acc >>"
            aws_secret_key = "<< pipeline.parameters.aws_auth_sec >>"
            access_ip      = "0.0.0.0/0"
            EOL
      - run:
          name: "see auth file"
          command: |
            apk update
            apk add jq
            cat terraform/terraform-aws-ec2-nginx-main/terraform.tfvars
            cd terraform/terraform-aws-ec2-nginx-main/
            terraform init
            terraform plan
            terraform apply -auto-approve
            terraform show -json | jq '.values.outputs.ec2_public_ip.value' > ip.txt
      - persist_to_workspace:
          root: terraform/terraform-aws-ec2-nginx-main
          paths:
            - key.pem
            - ip.txt
  
  install_istio:
    docker: 
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "test"
          command: |
            cd ./
            cat key.pem
            ip=$(sed 's/.//;s/.$//' ip.txt)
            ssh  -o BatchMode=yes -o StrictHostKeyChecking=no -i key.pem ubuntu@$ip


                         


workflows:
  say-hello-workflow:
    jobs:
      - create_vm
      - install_istio:
          requires:
            - create_vm
