# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  aws_auth_acc: 
    type: string
    default: $aws_auth_acc
  aws_auth_sec: 
    type: string
    default: $aws_auth_sec


jobs:
  create_vm:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: "create auth file"
          command: |
            cat > terraform/terraform-aws-ec2-nginx-main/terraform.tfvars \<< EOL
            aws_access_key = "<< pipeline.parameters.aws_auth_acc >>"
            aws_secret_key = "<< pipeline.parameters.aws_auth_sec >>"
            access_ip      = "0.0.0.0/0"
            EOL
      - run:
          name: "see auth file"
          command: |
            apk update
            apk add jq
            cat terraform/terraform-aws-ec2-nginx-main/terraform.tfvars
            cd terraform/terraform-aws-ec2-nginx-main/
            terraform init
            terraform plan
            terraform apply -auto-approve
            terraform show -json | jq '.values.outputs.ec2_public_ip.value' > ip.txt
      - persist_to_workspace:
          root: terraform/terraform-aws-ec2-nginx-main
          paths:
            - key.pem
            - ip.txt
  
  configure_minikube:
    docker: 
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "test"
          command: |
            sleep 240
            cd ./
            cat key.pem
            chmod 400 key.pem
            ip=$(sed 's/.//;s/.$//' ip.txt)
            ssh  -o BatchMode=yes -o StrictHostKeyChecking=no -i key.pem ubuntu@$ip \
            'sudo minikube start --vm-driver=none; sleep 120; sudo kubectl apply -f https://docs.projectcalico.org/manifests/calico-typha.yaml; sudo curl -L https://istio.io/downloadIstio | sh -'
  
  deploy_istio:
    docker: 
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "deploy_app"
          command: |
            sleep 120
            cd ./
            cat key.pem
            chmod 400 key.pem
            ip=$(sed 's/.//;s/.$//' ip.txt)
            ssh  -o BatchMode=yes -o StrictHostKeyChecking=no -i key.pem ubuntu@$ip \
            'cd istio-1.16.1; export PATH=$PWD/bin:$PATH; sudo istioctl install --set profile=demo -y; sudo kubectl label namespace default istio-injection=enabled; sudo kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml'
            ssh  -o BatchMode=yes -o StrictHostKeyChecking=no -i key.pem ubuntu@$ip \
            'cd istio-1.16.1; export PATH=$PWD/bin:$PATH; sudo kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml; export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}'); export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}'); export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}'); export INGRESS_HOST=$(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].status.hostIP}'); export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT; echo "$GATEWAY_URL"'

workflows:
  say-hello-workflow:
    jobs:
      - create_vm
      - configure_minikube:
          requires:
            - create_vm
      - deploy_istio:
          requires:
            - configure_minikube
